Provide loop-unwinding debugging instructions
model-checking/cbmc-training pull request #7
Opened 2022-07-05 10:29 UTC by tautschnig

Answer the question "how to debug unexpected loop unwinding," which has
come up multiple times in recent weeks (including
https://github.com/diffblue/cbmc/issues/6953).

Also includes a fix of a typo.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-05 18:34 UTC, markrtuttle requested changes

2022-07-05 18:34 UTC, markrtuttle commented on docs/src/faq/loop-unwinding.md
> +   bound using `--unwind` and also add --program-only. Pipe the output to some
Explain what program only is.  Most users have never heard of it.  Explain what kind of thing is being sent to standard output

2022-07-05 18:34 UTC, markrtuttle commented on docs/src/faq/loop-unwinding.md
> +5. The expression where you flip from is-a-constant to is-a-symbol is the
4

2022-07-05 18:34 UTC, markrtuttle commented on docs/src/faq/loop-unwinding.md
> +   issue or contribute a patch to address this.
Can you give a tiny code example of how to do this?

2022-07-06 13:02 UTC, tautschnig commented on docs/src/faq/loop-unwinding.md
> +   bound using `--unwind` and also add --program-only. Pipe the output to some
I've added half a sentence (and the example).

2022-07-06 13:02 UTC, tautschnig commented on docs/src/faq/loop-unwinding.md
> +   issue or contribute a patch to address this.
I've added an example.

2022-08-25 16:44 UTC, merged